[2023-12-09 17:06:56,022] [test_postgresdataapi] [consolelogger] [setUp:14] [INFO]: "Connected to the database."
[2023-12-09 17:06:56,022] [test_postgresdataapi] [consolelogger] [test_connection:27] [INFO]: "Connection test passed."
[2023-12-09 17:06:56,022] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."
.[2023-12-09 17:06:57,119] [test_postgresdataapi] [consolelogger] [setUp:14] [INFO]: "Connected to the database."
[2023-12-09 17:06:57,405] [postgresdataapi] [consolelogger] [execute_sql:58] [ERROR]: "Error executing SQL statement: cannot create temporary relation in non-temporary schema
LINE 1: CREATE TEMPORARY TABLE test_cicd.temp_query_status (query_id...
                               ^
"
[2023-12-09 17:06:57,505] [postgresdataapi] [consolelogger] [execute_sql:66] [ERROR]: "Error dropping temporary table: current transaction is aborted, commands ignored until end of transaction block
"
E[2023-12-09 17:06:57,505] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."
[2023-12-09 17:06:58,177] [test_postgresdataapi] [consolelogger] [setUp:14] [INFO]: "Connected to the database."
[2023-12-09 17:06:58,362] [postgresdataapi] [consolelogger] [execute_sql:58] [ERROR]: "Error executing SQL statement: relation "test_cicd.test_table" does not exist
LINE 1: SELECT * FROM test_cicd.test_table;
                      ^
"
[2023-12-09 17:06:58,362] [postgresdataapi] [consolelogger] [execute_sql:66] [ERROR]: "Error dropping temporary table: cannot access local variable 'temp_table_name' where it is not associated with a value"
E[2023-12-09 17:06:58,362] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."
[2023-12-09 17:06:59,048] [test_postgresdataapi] [consolelogger] [setUp:14] [INFO]: "Connected to the database."
[2023-12-09 17:06:59,233] [postgresdataapi] [consolelogger] [execute_sql:58] [ERROR]: "Error executing SQL statement: relation "test_cicd.non_existent_table" does not exist
LINE 1: SELECT * FROM test_cicd.non_existent_table;
                      ^
"
[2023-12-09 17:06:59,233] [postgresdataapi] [consolelogger] [execute_sql:66] [ERROR]: "Error dropping temporary table: cannot access local variable 'temp_table_name' where it is not associated with a value"
E[2023-12-09 17:06:59,233] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."

======================================================================
ERROR: test_create_table (__main__.TestPostgresDataAPI.test_create_table)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\tests\alight\foundation\postgres\test_postgresdataapi.py", line 32, in test_create_table
    self.data_api.execute_sql(sql_statement)
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\src\alight\foundation\postgres\postgresdataapi.py", line 44, in execute_sql
    self._cursor.execute(f"CREATE TEMPORARY TABLE test_cicd.{temp_table_name} (query_id UUID, status VARCHAR);")
psycopg2.errors.InvalidTableDefinition: cannot create temporary relation in non-temporary schema
LINE 1: CREATE TEMPORARY TABLE test_cicd.temp_query_status (query_id...
                               ^


======================================================================
ERROR: test_select_from_table (__main__.TestPostgresDataAPI.test_select_from_table)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\tests\alight\foundation\postgres\test_postgresdataapi.py", line 40, in test_select_from_table
    query_id, response = self.data_api.execute_sql(sql_statement)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\src\alight\foundation\postgres\postgresdataapi.py", line 36, in execute_sql
    self._cursor.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "test_cicd.test_table" does not exist
LINE 1: SELECT * FROM test_cicd.test_table;
                      ^


======================================================================
ERROR: test_table_not_created_in_schema (__main__.TestPostgresDataAPI.test_table_not_created_in_schema)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\tests\alight\foundation\postgres\test_postgresdataapi.py", line 49, in test_table_not_created_in_schema
    query_id, response = self.data_api.execute_sql(sql_statement)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\src\alight\foundation\postgres\postgresdataapi.py", line 36, in execute_sql
    self._cursor.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "test_cicd.non_existent_table" does not exist
LINE 1: SELECT * FROM test_cicd.non_existent_table;
                      ^


----------------------------------------------------------------------
Ran 4 tests in 4.426s

FAILED (errors=3)

